name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set working directory
        run: |
          mkdir -p /home/runner/work/flxtreme.github.io
          cd /home/runner/work/flxtreme.github.io

      - name: Install dependencies
        run: npm install

      - name: Linting
        working-directory: /home/runner/work/flxtreme.github.io
        run: npm run lint

      - name: Build and Export
        working-directory: /home/runner/work/flxtreme.github.io
        run: |
          npm run export
          npm run deploy